// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mizan.Infrastructure.Persistence;

#nullable disable

namespace Mizan.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mizan.Domain.Entities.FundDomain.Fund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Funds", (string)null);
                });

            modelBuilder.Entity("Mizan.Domain.Entities.StockDomain.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Stocks", (string)null);
                });

            modelBuilder.Entity("Mizan.Domain.Entities.StockDomain.StockDailyQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CouponNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CouponPaymentDate")
                        .HasColumnType("date");

                    b.Property<decimal>("DividendYield")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("PriceEarningRatio")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TradedVolume")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("TradingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("StockDailyQuotes", (string)null);
                });

            modelBuilder.Entity("Mizan.Domain.Entities.StockDomain.StockIRContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("StockIRContacts", (string)null);
                });

            modelBuilder.Entity("Mizan.Domain.Entities.FundDomain.Fund", b =>
                {
                    b.OwnsOne("Mizan.Domain.Entities.FundDomain.FundTickerSymbol", "BBGTicker", b1 =>
                        {
                            b1.Property<Guid>("FundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("FundId");

                            b1.ToTable("Funds");

                            b1.WithOwner()
                                .HasForeignKey("FundId");
                        });

                    b.OwnsOne("Mizan.Domain.Entities.Money", "NAV", b1 =>
                        {
                            b1.Property<Guid>("FundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("FundId");

                            b1.ToTable("Funds");

                            b1.WithOwner()
                                .HasForeignKey("FundId");
                        });

                    b.OwnsOne("Mizan.Domain.Entities.FundDomain.FundTickerSymbol", "RIC", b1 =>
                        {
                            b1.Property<Guid>("FundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("FundId");

                            b1.ToTable("Funds");

                            b1.WithOwner()
                                .HasForeignKey("FundId");
                        });

                    b.OwnsOne("Mizan.Domain.Entities.FundDomain.FundLiquidityProfile", "Liquidity", b1 =>
                        {
                            b1.Property<Guid>("FundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("RedemptionFrequency")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("SubscriptionFrequency")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("FundId");

                            b1.ToTable("Funds");

                            b1.WithOwner()
                                .HasForeignKey("FundId");
                        });

                    b.Navigation("BBGTicker");

                    b.Navigation("Liquidity");

                    b.Navigation("NAV")
                        .IsRequired();

                    b.Navigation("RIC");
                });

            modelBuilder.Entity("Mizan.Domain.Entities.StockDomain.Stock", b =>
                {
                    b.OwnsOne("Mizan.Domain.Entities.StockDomain.StockBasicData", "BasicData", b1 =>
                        {
                            b1.Property<Guid>("StockId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<string>("ISINCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<long>("ListedShares")
                                .HasColumnType("bigint");

                            b1.Property<DateOnly>("ListingDate")
                                .HasColumnType("date");

                            b1.Property<decimal>("ParValue")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)");

                            b1.Property<string>("ReutersCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Sector")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("SecurityType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("StockId");

                            b1.ToTable("Stocks");

                            b1.WithOwner()
                                .HasForeignKey("StockId");
                        });

                    b.Navigation("BasicData")
                        .IsRequired();
                });

            modelBuilder.Entity("Mizan.Domain.Entities.StockDomain.StockDailyQuote", b =>
                {
                    b.HasOne("Mizan.Domain.Entities.StockDomain.Stock", "Stock")
                        .WithMany("DailyQuotes")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Mizan.Domain.Entities.Money", "CashDividends", b1 =>
                        {
                            b1.Property<Guid>("StockDailyQuoteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("StockDailyQuoteId");

                            b1.ToTable("StockDailyQuotes");

                            b1.WithOwner()
                                .HasForeignKey("StockDailyQuoteId");
                        });

                    b.OwnsOne("Mizan.Domain.Entities.Money", "ClosingPrice", b1 =>
                        {
                            b1.Property<Guid>("StockDailyQuoteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("StockDailyQuoteId");

                            b1.ToTable("StockDailyQuotes");

                            b1.WithOwner()
                                .HasForeignKey("StockDailyQuoteId");
                        });

                    b.OwnsOne("Mizan.Domain.Entities.Money", "MarketCap", b1 =>
                        {
                            b1.Property<Guid>("StockDailyQuoteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("StockDailyQuoteId");

                            b1.ToTable("StockDailyQuotes");

                            b1.WithOwner()
                                .HasForeignKey("StockDailyQuoteId");
                        });

                    b.OwnsOne("Mizan.Domain.Entities.Money", "TradedValue", b1 =>
                        {
                            b1.Property<Guid>("StockDailyQuoteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("StockDailyQuoteId");

                            b1.ToTable("StockDailyQuotes");

                            b1.WithOwner()
                                .HasForeignKey("StockDailyQuoteId");
                        });

                    b.Navigation("CashDividends")
                        .IsRequired();

                    b.Navigation("ClosingPrice")
                        .IsRequired();

                    b.Navigation("MarketCap")
                        .IsRequired();

                    b.Navigation("Stock");

                    b.Navigation("TradedValue")
                        .IsRequired();
                });

            modelBuilder.Entity("Mizan.Domain.Entities.StockDomain.StockIRContact", b =>
                {
                    b.HasOne("Mizan.Domain.Entities.StockDomain.Stock", "Stock")
                        .WithMany("IRContacts")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Mizan.Domain.Entities.StockDomain.Stock", b =>
                {
                    b.Navigation("DailyQuotes");

                    b.Navigation("IRContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
